/*
 * RCC_cfg.h
 *
 *  Created on: Aug 16, 2022
 *      Author: Karim
 */

#ifndef MCAL_RCC_RCC_CFG_H_
#define MCAL_RCC_RCC_CFG_H_


#define RCC_HSI_ENABLE       ENABLE
#define RCC_HSE_ENABLE       DISABLE
#define RCC_PLL_ENABLE       DISABLE
#define RCC_CSS_ENABLE		 ENABLE
#define RCC_SYSTEM_CLK       RCC_HSE
#define RCC_HSE_BYPASS       NOT_BYPASS
/*
 * AHP peripherals clock options:
 	 * 1) RCC_AHB_SYSTEM_CLK
 	 * 2) RCC_AHB_SYSTEM_CLK_DIVIDED_BY_2
 	 * 3) RCC_AHB_SYSTEM_CLK_DIVIDED_BY_4
 	 * 4) RCC_AHB_SYSTEM_CLK_DIVIDED_BY_8
 	 * 5) RCC_AHB_SYSTEM_CLK_DIVIDED_BY_16
 	 * 6) RCC_AHB_SYSTEM_CLK_DIVIDED_BY_64
 	 * 7) RCC_AHB_SYSTEM_CLK_DIVIDED_BY_128
 	 * 8) RCC_AHB_SYSTEM_CLK_DIVIDED_BY_256
 	 * 9) RCC_AHB_SYSTEM_CLK_DIVIDED_BY_512
*/
#define RCC_AHB1_CLK		RCC_AHB1_SYSTEM_CLK

/*
 * APB1 peripherals clock options:
 	 * 1) RCC_APB1_AHB_CLK
 	 * 2) RCC_APB1_AHB_CLK_DIVIDED_BY_2
 	 * 3) RCC_APB1_AHB_CLK_DIVIDED_BY_4
 	 * 4) RCC_APB1_AHB_CLK_DIVIDED_BY_8
 	 * 5) RCC_APB1_AHB_CLK_DIVIDED_BY_16
*/
#define RCC_APB1_CLK	RCC_APB1_AHB_CLK

/*
 *APB2 peripherals clock options:
 	 * 1) RCC_APB2_AHB_CLK
 	 * 2) RCC_APB2_AHB_CLK_DIVIDED_BY_2
 	 * 3) RCC_APB2_AHB_CLK_DIVIDED_BY_4
   	 * 4) RCC_APB2_AHB_CLK_DIVIDED_BY_8
   	 * 5) RCC_APB2_AHB_CLK_DIVIDED_BY_16
*/
#define RCC_APB2_CLK	RCC_APB2_AHB_CLK

#endif /* MCAL_RCC_RCC_CFG_H_ */
